# Generated by Django 4.2.7 on 2023-12-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_subscribers_category_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
